"""create reviews table

Revision ID: 5466d7b33c90
Revises: 9d1135349bb2
Create Date: 2026-09-28 09:29:42.618363

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5466d7b33c90"
down_revision: str | Sequence[str] | None = "9d1135349bb2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("perfume_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("longevity", sa.Integer(), nullable=True),
        sa.Column("sillage", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "longevity BETWEEN 1 AND 5", name="ck_reviews_longevity_range"
        ),
        sa.CheckConstraint("rating BETWEEN 1 AND 10", name="ck_reviews_rating_range"),
        sa.CheckConstraint("sillage BETWEEN 1 AND 5", name="ck_reviews_sillage_range"),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["perfume_id"], ["perfumes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "author_id", "perfume_id", name="uq_reviews_author_id_perfume_id"
        ),
    )
    op.create_index(
        op.f("ix_reviews_author_id"), "reviews", ["author_id"], unique=False
    )
    op.create_index(
        op.f("ix_reviews_perfume_id"), "reviews", ["perfume_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reviews_perfume_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_author_id"), table_name="reviews")
    op.drop_table("reviews")
    # ### end Alembic commands ###
