"""create perfumes and perfume_notes tables

Revision ID: 7e9220502eaf
Revises: ef94a54ec5a9
Create Date: 2026-09-28 08:03:20.976864

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e9220502eaf"
down_revision: str | Sequence[str] | None = "ef94a54ec5a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "perfumes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("brand_id", sa.Integer(), nullable=False),
        sa.Column("release_year", sa.Integer(), nullable=True),
        sa.Column(
            "gender",
            sa.Enum(
                "masculine",
                "feminine",
                "unisex",
                name="gender",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "concentration",
            sa.Enum(
                "edc",
                "edt",
                "edp",
                "parfum",
                "extrait",
                name="concentration",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column("perfumer", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["brand_id"], ["brands.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("brand_id", "name", name="uq_perfumes_brand_id_name"),
    )
    op.create_index(
        op.f("ix_perfumes_brand_id"), "perfumes", ["brand_id"], unique=False
    )
    op.create_index(op.f("ix_perfumes_name"), "perfumes", ["name"], unique=False)
    op.create_table(
        "perfume_notes",
        sa.Column("perfume_id", sa.Integer(), nullable=False),
        sa.Column("note_id", sa.Integer(), nullable=False),
        sa.Column(
            "layer",
            sa.Enum(
                "top", "heart", "base", name="notelayer", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["note_id"], ["notes.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["perfume_id"], ["perfumes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("perfume_id", "note_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("perfume_notes")
    op.drop_index(op.f("ix_perfumes_name"), table_name="perfumes")
    op.drop_index(op.f("ix_perfumes_brand_id"), table_name="perfumes")
    op.drop_table("perfumes")
    # ### end Alembic commands ###
